### ISSUE TITLE
代码里有很多 RM.Subscriber 这个是从哪里引入的呢？

### ISSUE THREAD

**Issue by suncunhu** [redux-model/redux-model#1]
不是很懂这个 RM 有啥含义

**Comment by fwh1990** [comment]
@suncunhu RM是全局的namespace。在`index.d.ts`中可以看到。之所以用全局，主要为了避免import操作。然后RM就是Redux Model 的缩写，与其他库重复的可能性很小。  [https://github.com/fwh1990/redux-model-ts/blob/master/index.d.ts#L160](https://github.com/fwh1990/redux-model-ts/blob/master/index.d.ts#L160)

**Comment by fwh1990** [comment]
3.0版本之后基本不需要再业务项目里使用 RM.* 了，连业务上的类型约束都全部自动推导的。唯独这个`RM.Subscriber ` 需要在继承 subscriber 时使用。
```typescript
protected subscribers(): RM.Subscriber<Data> {
  return [
    someModel.someAction.onSuccess((state, action) => {
      return state;
    });
  ];
}
```
通过这种方式，其他模型onSuccess回调中的state的约束可以动态推导为当前模型
