### ISSUE TITLE
请问是否不通过useData拿数据 

### ISSUE THREAD

**Issue by XuJin186** [redux-model/redux-model#15]
现在有个权限鉴定  不需要监听数据来更改界面   所有有了这样子的需求  谢谢

**Comment by fwh1990** [comment]
useData是为了重渲染。如果不想重渲染，就用 data，这也是 connect() 模式下的
```typescript
const App: FC = () => {
  const myData = testModel.data.xxx;
  const others = testModel.data.yyy;

  return <div></div>;
};
```

`model.data` 可以用在任何地方

**Comment by XuJin186** [comment]
是我写法有问题  当initialState返回null的时候   data为空   我testModel.data.xxx的时候直接异常了
