### ISSUE TITLE
能不能支持下next.js

### ISSUE THREAD

**Issue by zhangwei900808** [redux-model/redux-model#16]
能不能支持下next.js

**Comment by fwh1990** [comment]
SSR吗，前两个月还想试着支持，后面一忙给忘了。尽快支持

**Comment by zhangwei900808** [comment]
@fwh1990 无意中搜索redux model发现了你的框架，非常喜欢，我现在用的是next.js+redux+redux-acitons+redux-saga，感觉好复杂，而你的框架感觉好方便，非常得心上手，希望尽快支持next.js，并加入到官方 的example里面，非常期待！

**Comment by zhangwei900808** [comment]
@fwh1990 忘了问了，框架支持redux-saga吗

**Comment by fwh1990** [comment]
为啥要支持saga？是什么场景？  

> @fwh1990 忘了问了，框架支持redux-saga吗

**Comment by zhangwei900808** [comment]
@fwh1990 方便异步接口的测试和可以随时取消相应的异步操作
