### ISSUE TITLE
交流贴

### ISSUE THREAD

**Issue by suncunhu** [redux-model/redux-model#2]
1. 是否可以在框架内部整合下 react-router, 像dva里model提供的subscriptions那种
2. 不知老哥是否了解过[akita](https://github.com/datorama/akita)这个框架, 不基于redux做的状态管理, 会不会有坑？

**Comment by fwh1990** [comment]
关于您希望的`react-router`操作，我想了解一下是在什么场景下会去使用，以及能否提供一段代码例子来配合使用场景。

**akita**我没用过，但是我看这个库的源码之后，发现akita主要是针对`angular`框架的，您去看package.json文件和examples目录，都能发现angular的影子。如果您正在使用React，那么我不建议使用akita这个库。

如果您不喜欢或者暂时没有考虑使用`redux-model-ts`，建议您使用`dvaJs`或者`rematch`，这两个都是很好的选择。但就typescript的支持度而言，`redux-model-ts`无疑拥有100%的业务无死角提示
