### ISSUE TITLE
v9.0.0讨论帖

### ISSUE THREAD

**Issue by fwh1990** [redux-model/redux-model#20]
目前正在制作模型9.0版本，主要是根据长期使用的一些心得，做一些破坏性更新，想办法让框架更加方便易用。

更新日志：https://github.com/redux-model/redux-model/blob/v9.x/CHANGELOG.md#900

如果您在使用过程中有任何的不爽或者建议意见，欢迎吐槽～

**Comment by fantasticsoul** [comment]
厉害了，看起来越来越易用了👍

**Comment by fwh1990** [comment]
> 厉害了，看起来越来越易用了👍

🙏感谢大佬关注，共同进步
