### ISSUE TITLE
redux-model交流

### ISSUE THREAD

**Issue by yoonzm** [redux-model/redux-model#29]
作者好，看了您的库觉得很nice，有一种相见恨晚的感觉。
因为对react及ts的喜爱，之前一直也在尝试开发一个类似的库，后面弄了一个简单版的在自用[easy-use-redux](https://github.com/yoonzm/easy-use-redux.git)(准备后面使用本库)，想与您探讨下。

## action显式声明
- 我之前一直考虑的是能否让用户感知不到action的存在，调用[model.method]即dispatch action，即会将所有method转换为action。
- 在您的库中发现需要显式的声明this.action()，不知道此处是否还有优化空间。

## 内置http服务
- 个人认为redux能够流行的其中一个原因就是其`简单`，只做一件事，甚至不直接支持异步等...
- 有的时候可能会使用sdk直接与后端进行通讯，即不会使用到库中的http服务，此时直接在action中发起请求也是可以的吧，这样做是否就享受不到loading状态了。

## immer
- 使用可观察对象来实现`model-data`，会导致不能使用`rest/spread`去merge`model-data`，感觉会有一丢丢的心智负担，不过问题不大，就是如果能尽量保留原始的使用方式最好不过了。

以上个人见解，有理解不到位的地方还请包涵。

**Comment by fwh1990** [comment]
Hello，感谢你对redux的热爱并为之添砖加瓦。


> * 我之前一直考虑的是能否让用户感知不到action的存在，调用[model.method]即dispatch action，即会将所有method转换为action。

自动转换的话不够灵活，因为方法有可能是用户自行封装的一个普通方法。或者考虑使用装饰器。

> * 在您的库中发现需要显式的声明this.action()，不知道此处是否还有优化空间。

这种方式是我重写了6个大版本之后才思考出的最简易方式，希望你能帮我想想。显式加入 this.action的好处有这些：
* 回调第一个参数就是state，无需再定义类型
* 订阅模式下可以自动推导该action的payload
* 让用户知道这是一个普通action，是用来更新reducer的
* this.action有第二个参数，可以处理更新后的逻辑





> * 个人认为redux能够流行的其中一个原因就是其`简单`，只做一件事，甚至不直接支持异步等...
> * 有的时候可能会使用sdk直接与后端进行通讯，即不会使用到库中的http服务，此时直接在action中发起请求也是可以的吧，这样做是否就享受不到loading状态了。

是的，加入http服务后，就不再是一个纯粹的状态库了。
redux-model的设计原则是：**只做TypeScript**，所以任何设计的考量都要先回答一个问题：对TS的支持度怎样？我会想尽一切办法让功能融入TS，该自动推导就绝不让用户写（推翻用TS降低开发效率的说辞）。
所以如果通过middleware来注入http或者用户使用完全独立的一个http库，那么用户就必须在http和model两边写类型。而且独立的http库，用户最后也是会或多或少去封装一层的。

另外其实不用内置的http库也是完全可以的，因为本来就是作为一个独立的功能。
```typescript
class TestModel extends Model {
  async fetch() {
    // 外部http服务
    const result = await myHttp.request(...);

    this.changeState((state) => {
      // 更新reducer
    });
  })

  async fetch2() {
    // 内置http可以独立使用
    await $api.getAsync(...);
  }
}
```
使用内置http的好处是：
* 不需要再关心http的实现
* 完美融合进redux，少写很多基础代码（大部分项目处理接口能占总action的85%）
* 少注入许多重复的类型定义
* loading, loadings, meta, throttle 马上就能用
* 订阅模式下可以自动推导该action的payload和response


> * 有的时候可能会使用sdk直接与后端进行通讯，即不会使用到库中的http服务，此时直接在action中发起请求也是可以的吧，这样做是否就享受不到loading状态了。

使用compose即可享受loading带来的乐趣

```typescript
class TestModel extends Model {
  fetch = this.compose(async () => {
    // 外部http服务
    const result = await myHttp.request(...);

    await ...

    this.changeState((state) => {
      // 更新reducer
    });

    await ...
  });
}

class model = new TestModel();

model.fetch.useLoading();
model.fetch.loading;
```


> * 使用可观察对象来实现`model-data`，会导致不能使用`rest/spread`去merge`model-data`，感觉会有一丢丢的心智负担，不过问题不大，就是如果能尽量保留原始的使用方式最好不过了。

对的，不能再用rest/spread，但是可以用`Object.assign(originData, newData)`，以及数组直接赋值，或者push，shift等操作，对象可以直接delete。

使用immer是因为受够了当数据结构较深，导致每一层都需要做rest/spread操作。不仅复杂，而且容易出错。



---------------------

总之，一切都是为了简化开发流程，简单粗暴并带点优雅，没必要为了写业务而加班和浪费时间。

**Comment by fwh1990** [comment]
内置http的唯一缺点就是：移植性太差，只能在特定平台使用

**Comment by yoonzm** [comment]
感谢回复。

> 显式action

对于此问题目前确实比较纠结，后面如果有什么好点子可以一点探讨下。

> 内置http的唯一缺点就是：移植性太差，只能在特定平台使用

尝试了下，内置http后也是可选的，就是有一点对于后面的维护来说可能稍会麻烦一些，比较依赖平台实现。

> 只做TypeScript

因为这个库之前的版本在rn的社区也看到过，当时看部分实现时就有这种感觉，其中对ts的提示有一种近乎极限的追求，你所说的（推翻用TS降低开发效率的说辞）我也是完全赞同，越来越能体会到ts给人那种满满的安全感

***
确实，如果从方便业务开发的角度出发的话，一切又都比较容易理解了。

**Comment by yoonzm** [comment]
不可否认这是一个优秀的库，我也很愿意用在自己的项目中，也希望后面在使用中会有机会给此项目贡献一点绵薄之力。
我会像身边的人推荐的，也期望这个库能被更多的人能看到。

**Comment by fwh1990** [comment]
http库还有一些东西可以做，比如请求失败时重试，token失效时的处理，通过制定标准的方案，能让项目更稳健。redux这块最近也在考虑加入computed state和ssr之类的东西。都已经有初步方案但是还没成型，不过一旦做好，意味着开发速度能再次上升（越到后面越难升）。

**Comment by fwh1990** [comment]
> 不可否认这是一个优秀的库，我也很愿意用在自己的项目中，也希望后面在使用中会有机会给此项目贡献一点绵薄之力。

只能说简单粗暴，算不上多优秀。如果你的easy-use-redux库没有投入太多或者还不够完善，而且如果你认同当前redux-model的框架理念，欢迎直接投入到这边，并一起完善它（提出建议或者PR）

> 我会像身边的人推荐的，也期望这个库能被更多的人能看到。

推广还是很难的，我已经放弃了，心累。一上来就是redux不香吗，mobx不香吗，dva不香吗？而且鉴于国内的开发者用TS的比例不高，能真正知道怎么用的更少，很多都在写anyscript，这一大群体根本体会不到类型提示带来的快感！

**Comment by yoonzm** [comment]
[握手]

**Comment by fwh1990** [comment]
随着个人水平的提升，重新设计了模型：https://github.com/foca-js/foca ，更加简洁，自然。欢迎尝试。

大部分思路都是借鉴redux-model，业务代码再次减少，同时解决了移植性差和请求库不够强大的问题。
