### ISSUE TITLE
Taro 3.1.22 版本 h5 模式下报错 3.0.22正常

### ISSUE THREAD

**Issue by lzhlo** [redux-model/redux-model#30]
> ./node_modules/@redux-model/taro/es/utils/getTaro.js
Module not found: Can't resolve '@tarojs/taro-h5' in 'D:\code\php\www\mobile\node_modules\@redux-model\taro\es\utils'

**Comment by fwh1990** [comment]
@tarojs/taro-h5 这个库你是否有安装呢

**Comment by lzhlo** [comment]
> @tarojs/taro-h5 这个库你是否有安装呢

已解决  taro升级 把h5组件升级没了
