### ISSUE TITLE
Array packing in wrong format in URL query params

### ISSUE THREAD

**Issue by DevanXU** [redux-model/redux-model#5]
I have a request which passed an array as query params in URL, e.g. "ids=[1]", it's supposed to be converted to "ids[]=1" but actually got "ids[0]=1".

**Comment by fwh1990** [comment]
How do you write request action? Can you paste core code to here ?

**Comment by fwh1990** [comment]
I have tested this case and I got expected format.
```typescript
class TestModel extends Model {
  myAction = api.action((ids) => {
      return this
        .get('/api/test')
        .query({
            ids: [1, 2]
        });
  });
}
```
The final url is : `xxx.com/api/test?ids[]=1&ids[]=2`

So, you should tell me which package are you using ?  `web`, `react-native` , `taro` or `vue`

**Comment by fwh1990** [comment]
I have fixed this problem here [commit](https://github.com/redux-model/redux-model/commit/80348cde2be0fcec1734836be95bcfb0e1f40507) if your are using `@redux-model/taro`, and I will publish new version after you confirm it

**Comment by fwh1990** [comment]
Hi, I have bumped new version `@redux-model/taro` to fix this problem.

**Comment by DevanXU** [comment]
Sorry, i should've reported the issue more clear. But you got it, it's on Taro. It's good to know it's been fixed already.
BTW, @redux-model is a good piece of work.

**Comment by fwh1990** [comment]
Feel free to use redux-model and give me more suggestion whenever you want, thank you.
